noticias/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    # ex: /noticias/
    url(r'^$', views.vernoticias, name='ver_noticias'),
     # ex: /noticias/5/
    url(r'^(?P<noticia_id>[0-9]+)/$', views.vernoticia, name='ver_noticia'),
    url(r'^introduirnoticia/$', views.intro_edit_noticia, name='nueva_noticia'),
    url(r'^editarnoticia/(?P<noticia_id>[0-9]+)/$', views.intro_edit_noticia, name='editar_noticia'),
    url(r'^eliminarnoticia/(?P<noticia_id>[0-9]+)/$', views.eliminarnoticia, name='eliminar_noticia'),

    #tags
    url(r'^tags/$', views.vertags, name='ver_tags'),
    url(r'^introduirtag/$', views.intro_edit_tag, name='nuevo_tag'),
    url(r'^editartag/(?P<tag_id>[0-9]+)/$', views.intro_edit_tag, name='editar_tag'),
    url(r'^eliminartag/(?P<tag_id>[0-9]+)/$', views.eliminartag, name='eliminar_tag'),

    #imagenes
    url(r'^imagenes/$', views.verimagenes, name='ver_imagenes'),
    url(r'^introduirimagen/$', views.intro_edit_imagen, name='nueva_imagen'),
    url(r'^editarimagen/(?P<imagen_id>[0-9]+)/$', views.intro_edit_imagen, name='editar_imagen'),
    url(r'^eliminarimagen/(?P<imagen_id>[0-9]+)/$', views.eliminarimagen, name='eliminar_imagen'),
]

proyecto1516/urls.py
# encoding: utf-8
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.contrib import admin
from usuarios import views as vista_usuarios
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    url(r'^admin/', admin.site.urls),
    url(r'^noticias/', include('noticias.urls', namespace='noticias')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login/', vista_usuarios.vista_login, name="login"),
    url(r'^registrar/', vista_usuarios.registrar, name="registrar"),
    url(r'^sortir/', vista_usuarios.logout_view, name="sortir"  ),

]

    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

noticias/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime

class Tag (models.Model):
    id = models.AutoField(primary_key = True, unique = True)
    nombre_tag = models.CharField(max_length=(100),help_text="Nombre del tag")
    def __str__(self):
        return '%s' % (self.nombre_tag)

class Imagen (models.Model):
    id = models.AutoField(primary_key = True, unique = True)
    titulo = models.CharField(max_length=100,help_text="El titulo de la imagen")
    imagen = models.ImageField(upload_to='imagenes')
    def __str__(self):
        return '%s' % (self.titulo)

class Noticia (models.Model):
    id = models.AutoField(primary_key = True, unique = True)
    titulo = models.CharField(max_length=100, help_text="Titulo de la noticia")
    subtitulo = models.CharField(max_length=200, help_text="Subtitulo de la noticia")
    entrada = models.CharField(max_length=500, help_text="Frase 1")
    cuerpo = models.TextField(max_length=1000, help_text="Frase 2 o Desarrollo noticia ")
    fecha_publicacion = models.DateTimeField('fecha de publicacion')
    votos = models.IntegerField(default=0)
    tag = models.ForeignKey(Tag)
    usuario = models.ForeignKey(User)
    imagenes = models.ManyToManyField(Imagen, related_name="noticias")
    def __str__(self):
        return '%s' % (self.titulo)

    def publicacion_reciente(self):
        return self.fecha_publicacion >= timezone.now() - datetime.timedelta(days=1)

class Comentario(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    comentario = models.CharField(max_length=500, help_text="Comentario")
    fecha_publicacion = models.DateTimeField('fecha de publicacion')
    usuario = models.ForeignKey(User)
    noticia = models.ForeignKey(Noticia)
    def __str__(self):
        return '%s' % (self.comentario)

    def publicacion_reciente(self):
       return self.fecha_publicacion >= timezone.now() - datetime.timedelta(days=1)

noticias/views.py
from noticias.models import Noticia, Tag, Imagen
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.forms import modelform_factory
from django.contrib import messages
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.auth.decorators import login_required

def vernoticias(request):
    noticias = Noticia.objects.all()
    return render(request, 'noticias/noticia.html', {'noticias': noticias})

def vernoticia(request, noticia_id):
    noticia = get_object_or_404(Noticia, pk=noticia_id)
    return render(request, 'noticias/detalle.html', {'noticia':noticia})

@login_required
def intro_edit_noticia(request, noticia_id=None):
    es_modificacio =(noticia_id!=None)
    noticiaForm =modelform_factory(Noticia,exclude=('id','usuario',))
    if es_modificacio:
        noticia = get_object_or_404(Noticia, id=noticia_id)
    else:
        noticia=Noticia()
    if request.method == 'POST':
        form = noticiaForm(request.POST,request.FILES,instance=noticia)
        if form.is_valid():
            form.instance.usuario = request.user
            noticia = form.save()
            if(es_modificacio):
                messages.add_message(request, messages.SUCCESS, 'Modificado correctamente')
            else:
                messages.add_message(request, messages.SUCCESS, 'Creado correctamente ')
            return HttpResponseRedirect(reverse('noticias:ver_noticias'))
        else:
            if(es_modificacio):
                messages.add_message(request, messages.ERROR, 'Error en la modificacion de la noticia')
            else:
                messages.add_message(request, messages.ERROR, 'Error en crear la noticia')
    else:
        form = noticiaForm(instance=noticia)

    form.helper = FormHelper()
    form.helper.form_class = 'form-horizontal col-md-8 col-md-offset-2'
    form.helper.label_class = 'col-lg-3'
    form.helper.field_class = 'col-lg-8 col-md-8'
    form.helper.add_input(Submit('submit', 'Enviar'))
    return render(request, 'formulario.html', {'form': form, 'noticia':noticia})
@login_required
def eliminarnoticia(request, noticia_id):
    noticia = get_object_or_404(Noticia, pk=noticia_id)
    messages.add_message(request, messages.SUCCESS,'La noticia he sido borrado correctamente')
    noticia.delete()
    return HttpResponseRedirect(reverse('noticias:ver_noticias') )

###Tags ###
@login_required
def vertags(request):
    tags = Tag.objects.all()
    return render(request, 'noticias/tag.html', {'tags': tags})
@login_required
def intro_edit_tag(request, tag_id=None):
    es_modificacio =(tag_id!=None)
    tagForm =modelform_factory(Tag, exclude=('id',))
    if es_modificacio:
        tag = get_object_or_404(Tag, id=tag_id)
    else:
        tag=Tag()
    if request.method == 'POST':
        form = tagForm(request.POST,request.FILES,instance=tag)
        if form.is_valid():
            tag = form.save()
            if(es_modificacio):
                messages.add_message(request, messages.SUCCESS, 'Modificado correctamente')
            else:
                messages.add_message(request, messages.SUCCESS, 'Creado correctamente ')
            return HttpResponseRedirect(reverse('noticias:ver_tags'))
        else:
            if(es_modificacio):
                messages.add_message(request, messages.ERROR, 'Error en la modificacion del tag')
            else:
                messages.add_message(request, messages.ERROR, 'Error en crear el tag')
    else:
        form = tagForm(instance=tag)

    form.helper = FormHelper()
    form.helper.form_class = 'form-horizontal col-md-6 col-md-offset-3'
    form.helper.label_class = 'col-lg-3'
    form.helper.field_class = 'col-lg-8 col-md-8'
    form.helper.add_input(Submit('submit', 'Enviar'))
    return render(request, 'formulario.html', {'form': form, 'tag':tag})
@login_required
def eliminartag(request, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id)
    messages.add_message(request, messages.SUCCESS,'El tag he sido borrado correctamente')
    tag.delete()
    return HttpResponseRedirect(reverse('noticias:ver_tags') )

#imagenes
@login_required
def verimagenes(request):
    imagenes = Imagen.objects.all()
    return render(request, 'noticias/imagen.html', {'imagenes': imagenes})
@login_required
def intro_edit_imagen(request, imagen_id=None):
    es_modificacio =(imagen_id!=None)
    imagenForm =modelform_factory(Imagen,exclude=('id','imagen2',))
    if es_modificacio:
        imagen = get_object_or_404(Imagen, id=imagen_id)
    else:
        imagen=Imagen()
    if request.method == 'POST':
        form = imagenForm(request.POST,request.FILES,instance=imagen)
        if form.is_valid():
            imagen = form.save()
            if(es_modificacio):
                messages.add_message(request, messages.SUCCESS, 'Modificado correctamente')
            else:
                messages.add_message(request, messages.SUCCESS, 'Creado correctamente ')
            return HttpResponseRedirect(reverse('noticias:ver_imagenes'))
        else:
            if(es_modificacio):
                messages.add_message(request, messages.ERROR, 'Error en la modificacion de la imagen')
            else:
                messages.add_message(request, messages.ERROR, 'Error en crear la imagen')
    else:
        form = imagenForm(instance=imagen)

    form.helper = FormHelper()
    form.helper.form_class = 'form-horizontal col-md-6 col-md-offset-3'
    form.helper.label_class = 'col-lg-3'
    form.helper.field_class = 'col-lg-8 col-md-8'
    form.helper.add_input(Submit('submit', 'Enviar'))
    return render(request, 'formulario.html', {'form': form, 'imagen':imagen})

@login_required
def eliminarimagen(request, imagen_id):
    imagen = get_object_or_404(Imagen, pk=imagen_id)
    messages.add_message(request, messages.SUCCESS,'El tag he sido borrado correctamente')
    imagen.delete()
    return HttpResponseRedirect(reverse('noticias:ver_imagenes') )

noticias/templates/noticias/detalle.html
{%extends 'base.html' %}

{%block content%}
    <div class="row">
        <div class="col-md-12">
            <div class="col-lg-12">
                <div class="text-right row">
                    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.6&appId=259837021031249";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
                </div>
                <h6 class="description">Noticia </h6>
                <div class="row pt-md">
                    {% if noticia %}

                        <p> {{ noticia.titulo }}</p>

                        {% for imagen in noticia.imagenes.all %}
                                        <img src="{{ imagen.imagen.url }}" class="img-responsive img-clip-not">
                                    {% endfor %}

                        <p> {{ noticia.subtitulo }}</p>
                        <p> {{ noticia.entrada }}</p>
                        <p> {{ noticia.cuerpo }}</p>
                        <p> {{ noticia.usuario }}</p>
                        <p> {{ noticia.fecha_publicacion }}</p>
                        <p> {{ noticia.votos }}</p>
                        <p> {{ noticia.tag }}</p>

                        <h6 class="description">Comentarios</h6>

                        <div class="fb-comments" data-href="http://www.mflores.bol:8000/noticias/1/" data-numposts="5"></div>
                    {% else %}
                        <p>No hay la noticia demandada  </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{%endblock%}

noticias/templates/noticias/imagen.html
{%extends 'base.html' %}
{% load staticfiles %}

{% block header %}
    <link href="{% static 'noticias/css/style.css' %}" rel="stylesheet" media="screen">
{% endblock %}

{%block content%}
    <div class="row">
        <div class="col-md-12">
            <div class="col-lg-12">
                <div class="text-right row">
                    <a href="{% url 'noticias:nueva_imagen'%}" class="btn btn-sm btn-success text-right"><span class="fa fa-plus"></span> Nueva Imagen</a>
                </div>
                <h6 class="description">Imagenes</h6>
                <div class="row pt-md">
                    {% if imagenes %}

                        {% for imagen in imagenes %}

                            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 profile">
                                <div class="img-box">
                                    <img src="{{ imagen.imagen.url }}" class="img-responsive img-clip">
                                    <ul class="text-center">
                                        <a href="{% url 'noticias:editar_imagen' imagen.id %}"><li><i class="fa fa-pencil"></i></li></a>
                                        <a href="{% url 'noticias:eliminar_imagen' imagen.id %}"><li><i class="fa fa-trash"></i></li></a>
                                    </ul>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>No hay Imagenes </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{%endblock%}

noticias/templates/noticias/noticia.html
{%extends 'base.html' %}
{% load staticfiles %}

{% block header %}
    <link href="{% static 'noticias/css/style.css' %}" rel="stylesheet" media="screen">
{% endblock %}

{%block content%}




    <div class="row">
        <div class="col-md-12">
            <div class="col-lg-12">
                <div class="text-right row">
                    <a href="{% url 'noticias:nueva_noticia'%}" class="btn btn-sm btn-success text-right"><span class="fa fa-plus"></span> Nueva Noticia</a>
                </div>
                <h6 class="description">Noticias</h6>
                <div class="row pt-md">
                    {% if noticias %}
                        <div class="col-xs-12  col-sm-12 ">

                            <section>
                                <div class="row">
                                    <div class="col-lg-9">
                                        {% for noticia in noticias %}
                                            <div class="row" >
                                                <div class="categoria-articulo">
                                                    <span>
                                                        <a href="#">{{ noticia.tag }}</a>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="row noticia-general">
                                            <div class="titulo-noticia">
                                                <h2 class="text-justify noticia-detalles">
                                                    <a href="{% url 'noticias:ver_noticia' noticia.id %}"> {{ noticia.titulo }}</a>
                                                </h2>
                                            </div>

                                            <div class="row">
                                                <div class="col-lg-2 noticia-detalles">
                                                    <a href="#" rel="author"><b>{{ noticia.usuario }}</b></a>
                                                </div>
                                                <div class="col-lg-3">
                                                    <time title="2016-05-24T14:54:52Z" datetime="1464101692">{{ noticia.fecha_publicacion }}</time>
                                                </div>
                                            </div>
                                            <div class="text-center img-box">
                                                {% for imagen in noticia.imagenes.all %}
                                                    <img src="{{ imagen.imagen.url }}" class="img-responsive imagen-noticia">
                                                {% endfor %}
                                            </div>
                                            <div >
                                                <div >
                                                    <div ></div>
                                                    <p class="text-justify noticia-detalles">{{ noticia.entrada }}</p>
                                                    <p class="text-justify noticia-detalles">{{ noticia.cuerpo }}</p>
                                                </div>
                                            </div>



                                            <div class="row">
                                                <div class="col-lg-7 noticia-detalles">
                                                    <p>Compartir</p>
                                                    <ul>
                                                        <li><a href="http://www.facebook.com/dialog/feed?app_id=360028941603&redirect_uri=http%3A%2F%2Fwww.genbeta.com%2F&link=http://www.genbeta.com/redes-sociales-y-comunidades/confirmado-twitter-excluira-imagenes-y-nombres-de-usuario-de-su-limite-de-140-caracteres" class="btn-facebook js-btn-facebook" data-postname="confirmado-twitter-excluira-imagenes-y-nombres-de-usuario-de-su-limite-de-140-caracteres">Facebook</a></li>
                                                        <li><a href="https://twitter.com/intent/tweet?url=http://www.genbeta.com/p/205138&text=Confirmado%3A%20Twitter%20excluir%C3%A1%20im%C3%A1genes%20y%20nombres%20de%20usuario%20de%20su%20l%C3%ADmite%20de%20140%20caracteres&via=genbeta" class="btn-twitter js-btn-twitter" data-postname="confirmado-twitter-excluira-imagenes-y-nombres-de-usuario-de-su-limite-de-140-caracteres">Twitter</a></li>
                                                        <li><a href="mailto:?subject=Confirmado: Twitter excluirá imágenes y nombres de usuario de su límite de 140 caracteres&body=http://www.genbeta.com/redes-sociales-y-comunidades/confirmado-twitter-excluira-imagenes-y-nombres-de-usuario-de-su-limite-de-140-caracteres?utm_source=sharebutton&amp;utm_medium=email&amp;utm_content=POST&amp;utm_campaign=24_May_2016%26utm_term%3DCLICK%2BON%2BTITLE" class="btn-email js-btn-email" data-postname="confirmado-twitter-excluira-imagenes-y-nombres-de-usuario-de-su-limite-de-140-caracteres">E-mail</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-lg-4">
                                                    <a href="{% url 'noticias:ver_noticia' noticia.id %}">Leer más &raquo;</a>
                                                </div>

                                                <a class="btn btn-success" role="button" href="{% url 'noticias:editar_noticia' noticia.id %}">Editar</a> <a class="btn btn-danger" role="button" href="{% url 'noticias:eliminar_noticia' noticia.id %}">Eliminar</a>
                                            </div>
                                            </div>
                                        {% endfor %}

                                    </div>
                                    <div class="col-lg-3">
                                        <p>aqui tenemos 3 espacios</p>
                                    </div>
                                </div>
                            </section>
                        </div>
                    {% else %}
                        <p>No hay Noticias </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{%endblock%}

noticias/templates/noticias/tag.html
{%extends 'base.html' %}
{%block content%}
    <div class="row">
        <div class="col-md-12">
            <div class="col-lg-12">
                <div class="text-right row">
                    <a href="{% url 'noticias:nuevo_tag'%}" class="btn btn-sm btn-success text-right"><span class="fa fa-plus"></span> Nuevo Tag</a>
                </div>
                <h6 class="description">Imagenes</h6>
                <div class="row pt-md">
                    {% if tags %}
                        <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Nombre</th>
                                    <th>Opciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for tag in tags %}
                                    <tr>
                                        <td> {{ tag.id }}</td>
                                        <td> {{ tag.nombre_tag}}</td>
                                        <td><a class="btn btn-success" role="button" href="{% url 'noticias:editar_tag' tag.id %}">Editar</a> <a class="btn btn-danger" role="button" href="{% url 'noticias:eliminar_tag' tag.id %}">Eliminar</a> </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% else %}
                        <p>No hay Tags </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{%endblock%}