noticias/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    # ex: /noticias/
    url(r'^$', views.vernoticias, name='ver_noticias'),
     # ex: /noticias/5/
    url(r'^(?P<noticia_id>[0-9]+)/$', views.vernoticia, name='ver_noticia'),
    url(r'^introduirnoticia/$', views.intro_edit_noticia, name='nueva_noticia'),
    url(r'^editarnoticia/(?P<noticia_id>[0-9]+)/$', views.intro_edit_noticia, name='editar_noticia'),
    url(r'^eliminarnoticia/(?P<noticia_id>[0-9]+)/$', views.eliminarnoticia, name='eliminar_noticia'),

    #tags
    url(r'^tags/$', views.vertags, name='ver_tags'),
    url(r'^introduirtag/$', views.intro_edit_tag, name='nuevo_tag'),
    url(r'^editartag/(?P<tag_id>[0-9]+)/$', views.intro_edit_tag, name='editar_tag'),
    url(r'^eliminartag/(?P<tag_id>[0-9]+)/$', views.eliminartag, name='eliminar_tag'),

    #imagenes
    url(r'^imagenes/$', views.verimagenes, name='ver_imagenes'),
    url(r'^introduirimagen/$', views.intro_edit_imagen, name='nueva_imagen'),
    url(r'^editarimagen/(?P<imagen_id>[0-9]+)/$', views.intro_edit_imagen, name='editar_imagen'),
    url(r'^eliminarimagen/(?P<imagen_id>[0-9]+)/$', views.eliminarimagen, name='eliminar_imagen'),
]

proyecto1516/urls.py
# encoding: utf-8
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.contrib import admin
from usuarios import views as vista_usuarios
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    url(r'^admin/', admin.site.urls),
    url(r'^noticias/', include('noticias.urls', namespace='noticias')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login/', vista_usuarios.vista_login, name="login"),
    url(r'^registrar/', vista_usuarios.registrar, name="registrar"),
    url(r'^sortir/', vista_usuarios.logout_view, name="sortir"  ),

]

    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{{titol|default:"Noticias"}}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/menu-theme.css' %}" rel="stylesheet" media="screen">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    {% block header %}

    {%endblock%}
</head>

<body>

<!-- Fixed navbar -->
<nav id="header" class="navbar navbar-fixed-top">
    <div id="header-container" class="container navbar-container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a id="brand" class="navbar-brand" href="#">{{request.user}}</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2 navbar">
            <ul class="nav navbar-nav">
                {#            {% if user.is_authenticated %}#}
                <li class="active"><a href="{% url 'noticias:ver_noticias' %}"> Noticias <span class="sr-only">(current)</span></a></li>
                <li><a href=""> Tags fuera</a></li>
                <li><a href="{% url 'noticias:ver_imagenes' %}"> Imagenes </a></li>
                <li><a href="#"> Paginas Amigas </a></li>
                <li><a href="#"> Curriculum  </a></li>
                <!--<li><a href="#"> Maquinaria </a></li>-->
                <!--<li><a href="#"> Alquiler de maquinaria</a></li>
                <li><a href="#"> Paginas Amigas</a></li>
                <li><a href="#"> Quienes somos </a></li>-->
                <li><a href="#"> Videos </a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class=" dropdown"><a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Opciones <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% if user.is_staff %}
                            <li><a href="#">Cambiar Contraseña</a></li>
                                {% endif %}
                            <li><a href="#">Mi Perfil</a></li>
                        </ul>

                    <li><a href="{% url 'sortir' %}">Sortir</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Connectar-se</a></li>
                    <li><a href="{% url 'registrar' %}">Registrar-se</a></li>
                {% endif %}
            </ul>
        </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->

{% if user.is_staff %}



    <div class="container" style="padding-top: 70px;">
     {% if messages %}
        {% for message in messages %}
            <div class="alert alertes alert-{{ message.tags }} " role="alert">{{message}}</div>
        {% endfor %}
    {% endif %}
    <div class="panel panel-primary">
            <div class="panel-heading text-center">PANEL DE ADMINISTRACION</div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-2">
                          <ul class="nav nav-pills nav-stacked">
                              <li class="active"><a href="#">Menu</a></li>
                              <li><a href="{% url 'noticias:ver_noticias' %}">Noticias</a></li>
                              <li class="disabled"><a href="#">Disabled</a></li>
                              <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                                  Dropdown <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                  <li><a href="#">Action</a></li>
                                  <li><a href="#">Another action</a></li>
                                  <li><a href="#">Something else here</a></li>
                                  <li class="divider"></li>
                                  <li><a href="#">Separated link</a></li>
                                </ul>
                              </li>
                              <li><a href="#">Action 2</a></li>
                              <li><a href="#">Action 3</a></li>
                              <li><a href="#">Action 4</a></li>
                              <li><a href="#">Action 5</a></li>
                              <li><a href="#">Action 6</a></li>
                              <li><a href="#">Action 7</a></li>
                              <li><a href="#">Action 8</a></li>
                              <li><a href="#">Action 9</a></li>
                              <li><a href="#">Action 10</a></li>
                              <li><a href="#">Action 11</a></li>
                              <li><a href="#">Action 12</a></li>
                         </ul>
                    </div>
                    <div class="col-lg-10">
                        <div class="row">
                            <div class="col-lg-6">
                                  <div class="panel panel-primary">
                                      <div class="panel-heading">Graph 1</div>
                                      <div class="panel-body">
                                        <div id="chart1" class="c3" style="max-height: 320px; position: relative;"><div class="c3-tooltip-container" style="position: absolute; pointer-events: none; display: none; top: 65.5px; left: 64.5px;"><table class="c3-tooltip"><tbody><tr><th colspan="2">0</th></tr><tr class="c3-tooltip-name-data1"><td class="name"><span style="background-color:#1f77b4"></span>data1</td><td class="value">90</td></tr><tr class="c3-tooltip-name-data2"><td class="name"><span style="background-color:#ff7f0e"></span>data2</td><td class="value">120</td></tr><tr class="c3-tooltip-name-data3"><td class="name"><span style="background-color:#2ca02c"></span>data3</td><td class="value">300</td></tr></tbody></table></div></div>
                                      </div>
                                  </div>
                            </div>
                            <div class="col-lg-6">
                                  <div class="panel panel-primary">
                                      <div class="panel-heading">Graph 2</div>
                                      <div class="panel-body">
                                        <div id="chart2" class="c3" style="max-height: 320px; position: relative;"><div class="c3-tooltip-container" style="position: absolute; pointer-events: none; display: none;"></div></div>
                                      </div>
                                  </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                  <div class="panel panel-primary">
                                      <div class="panel-heading">Graph 3</div>
                                      <div class="panel-body">
                                        <div id="chart3" class="c3" style="max-height: 320px; position: relative;"><div class="c3-tooltip-container" style="position: absolute; pointer-events: none; display: none; top: 131.5px; left: 69.5px;"><table class="c3-tooltip"><tbody><tr><th colspan="2">0</th></tr><tr class="c3-tooltip-name-data1"><td class="name"><span style="background-color:#1f77b4"></span>data1</td><td class="value">300</td></tr><tr class="c3-tooltip-name-data2"><td class="name"><span style="background-color:#ff7f0e"></span>data2</td><td class="value">130</td></tr></tbody></table></div></div>
                                      </div>
                                  </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
</div>




{% else %}




    <div class="container" style="padding-top: 70px;">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alertes alert-{{ message.tags }} " role="alert">{{message}}</div>
        {% endfor %}
    {% endif %}

    {% block content %}

    {%endblock%}


    <div class="footer">
        {% block footer %}

        {%endblock%}
    </div>
</div>



{% endif %}

<script src="{% static 'js/jquery-1.11.3.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/funciones.js' %}"></script>
<script src="{% static 'js/menu-theme.js' %}"></script>
{%block scripts %}

{%endblock%}
<footer>
    <div class="container">
        <div class="col-md-10 col-md-offset-1 text-center">
            <h6>Coded with <i class="fa fa-heart red"></i> by <a href="http://www.nabeel.co.in" target="_blank">Mario Flores</a></h6>
        </div>
    </div>
</footer>
</body>

</html>

templates/formulario.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}

{%block content%}
    <div class="row">
        {% crispy form %}
    </div>
    <div class="row">
        <a href="{% url 'social:begin' 'twitter' %}"> Twitter Login</a>
        <a href="{% url 'social:begin' 'facebook' %}"> Facebook Login</a>
    </div>
{%endblock content%}